[profile.default]
src = "src"
out = "out"
libs = ["lib"]
evm_version = "cancun"
gas_reports_ignore = ["SecurityProxy", "LogicContract"]

[rpc_endpoints]
deploy = "${DEPLOY_RPC}"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
